### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jacktan1** [UBC-MDS/DSCI_522_group408#37]
- Feature engineering (why choose the features that we did?)
- Forward selection (pick the best, and then see which one minimizes the loss the most, and then go from there)
- Have better names/legend for feature importance plots 
- Plots have different color backgrounds :)

**Comment by Zhang-Haipeng** [comment]
* Give rationale to using "5-game-average" as the baseline.

**Comment by jnederlo** [comment]
- The Feature Engineering is explained in the report (combination of correlations and domain knowledge).
- A forward selection algorithm could be used, but isn't really necessary as we only really have 3 explanatory features anyways. Reducing the features won't improve performance in this case, and because we already know the important features, won't help with explanation.
- The names on the plots are as descriptive as possible, they are thoroughly explained in the report.
- Added rationale for 5-game-average as the baseline.

All of the above changes have been reflected in PR #39.
